# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProyectoIOS1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProyectoIOS1
   
  
  # add the Firebase pod for Google Analytics
   pod 'Firebase/Analytics'
   pod 'Firebase/Auth'
   pod 'Firebase/Storage'
   pod 'FirebaseUI/Storage'
   pod 'Firebase/Core'
   pod 'Firebase/Firestore'
   pod 'FirebaseFirestoreSwift'
   

end
